import { useWallet } from '@solana/wallet-adapter-react';
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Download() {
  const [cid, setCid] = useState('');
  const [decrypt_key, setDecryptKey] = useState('');
  const { publicKey, sendTransaction, connected, connecting } = useWallet();

  async function onSave() {
    if (!cid || !publicKey) return;
    const response = await fetch('/api/precrypt/' + cid, {
      method: 'GET'
    });
    const json = await response.json();
    setDecryptKey(json);
  }

  function onDownload() {
    const blob = new Blob([decrypt_key], {type: 'text/csv'});
    const elem = window.document.createElement('a');
    elem.href = window.URL.createObjectURL(blob);
    elem.download = "decrypt.json";        
    document.body.appendChild(elem);
    elem.click();        
    document.body.removeChild(elem);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Upload</a> your keys
        </h1>

        <WalletMultiButton />

        <label>
          CID: 
          <input
            type={'text'}
            onChange={(e) => setCid(e.target.value)}
            value={cid}
          />
        </label>
        <button
          disabled={!cid || !publicKey}
          onClick={onSave}
        >
          Submit
        </button>

        {decrypt_key && <button onClick={onDownload}>Download Decryption Key</button>}
      </main>
    </div>
  );
}