import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Precrypt</a>
        </h1>

        <div className={styles.grid}>
          <a href="/upload" className={styles.card}>
            <h2>Upload &rarr;</h2>
            <p>Store your recryption keys on this node so that your token holders can access your encrypted files.</p>
          </a>

          <a href="/download" className={styles.card}>
            <h2>Download &rarr;</h2>
            <p>Retrieve decryption keys by verifying that you own the token associated with the requested file.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
